### ISSUE TITLE
What's rsolns for?

### ISSUE THREAD

**Issue by lizhengning** [jonathanventura/multi-camera-motion#1]
Hi

I am try to use the minimal solution of the generalized camera model, and I wonder what's does result rsolns mean? Does it stand for the rotation matrix, but it's quite different with the rotation I simulated. Or do I have to simulate small motion?

Cound you give an examples for the motion estimation?

**Comment by jonathanventura** [comment]
Hi,

Each "rsoln" is a 3x1 vector r corresponding to an first-order approximated rotation matrix.  For clarity I wrote up in a PDF how to obtain a rotation matrix from it.

[RotationExplanation.pdf](https://github.com/jonathanventura/multi-camera-motion/files/481576/RotationExplanation.pdf)
