### ISSUE TITLE
How to compute matrix A?

### ISSUE THREAD

**Issue by Torchmm** [jonathanventura/multi-camera-motion#2]
hello, thank you for your nice work!! but how to compute matrix A(15,35)?

**Comment by jonathanventura** [comment]
Thank you!  Look at Section 3 of the paper to see how the A matrix is formed:

https://openaccess.thecvf.com/content_iccv_2015/papers/Ventura_An_Efficient_Minimal_ICCV_2015_paper.pdf

**Comment by jonathanventura** [comment]
The function computeA in approx_relpose_generalized_fast_computeA.cpp does this computation.
